#!/bin/bash

#Setup binaries
FREEMEMORY='/bin/free'
QUOTA='/bin/quota'
DISKFREE='/bin/df'
GROUPNAME='/bin/groups'
HISTORY='/bin/history'

#Seletion
option=$1

#Check if there is an option entered
if [ -z "$option" ]
then
exit
fi

#Check option value
case "$option" in
quota)
    $QUOTA -s
;;
freemem)
    $FREEMEMORY -mh
;;
diskfree)
    $DISKFREE -h 2>/dev/null | less
;;
groups)
    $GROUPNAME $LOGNAME
;;
history)
    $HISTORY | less
esac
