#!/bin/bash -i

#Setup binaries
FREEMEMORY="/bin/free"
QUOTA="/bin/quota"
DISKFREE="/bin/df"
GROUPNAME="/bin/groups"

# Store the argument for the script
OPTION=$1

#Check if there is an option entered
if [[ -z "$OPTION" ]]; then
    exit -1
fi

#Check option value
case "$OPTION" in
    quota)
        $QUOTA -s
    ;;
    freemem)
        $FREEMEMORY -mh
    ;;
    diskfree)
        $DISKFREE -h 2>/dev/null | less
    ;;
    groups)
        $GROUPNAME "$LOGNAME"
    ;;
    history)
        history | less
    ;;
esac
exit 0
