#!/bin/bash

PRINTF="/usr/bin/printf"
CLEAR="/usr/bin/clear"

QUIT=0
SUBMENU=0

function display_menu {
    $CLEAR
    DISPLAYED_MENU=$1
    $DISPLAYED_MENU
}

function main_menu {
    $PRINTF "####################################################\n"
    $PRINTF "#\n"
    $PRINTF "# Welcome to the system manager\n"
    $PRINTF "# -----------------------------\n"
    $PRINTF "#\n"
    $PRINTF "# Please select a menu item\n"
    $PRINTF "#\n"
    $PRINTF "# 1) basic menu options\n"
    $PRINTF "# 2) advanced menu options\n"
    $PRINTF "# 3) passwd file options\n"
    $PRINTF "# 4) quit\n"
    $PRINTF "#\n"
    #$PRINTF "\r\r\r############################"
    $PRINTF "# Please enter a choice: "
    read CHOICE
    $PRINTF "####################################################\n"
}

function basic_menu {
    $PRINTF "####################################################\n"
    $PRINTF "# Basic Tasks Menu\n"
    $PRINTF "# ----------------\n"
    $PRINTF "#\n"
    $PRINTF "# 1) Show free memory\n"
    $PRINTF "# 2) Show free disk space\n"
    $PRINTF "# 3) Show disk quota\n"
    $PRINTF "# 4) Show the groups I am a member of\n"
    $PRINTF "# 5) Show the history of the commands for bash\n"
    $PRINTF "# 6) Quit this menu\n#\n"
    $PRINTF "# Please enter an option: "
    read CHOICE
    $PRINTF "####################################################\n\n"
}



while [[ $QUIT -eq "0" ]]; do
    display_menu main_menu
    SUBMENU=0
    
    case $CHOICE in 
        1)

            while [[ $SUBMENU -eq "0" ]]; do
                display_menu basic_menu
                case $CHOICE in
                1)
                    ./basic freemem
                    SUBMENU=1
                    QUIT=1
                    ;;
                2)
                    ./basic diskfree
                    SUBMENU=1
                    QUIT=1
                    ;;
                3)
                    ./basic quota
                    SUBMENU=1
                    QUIT=1
                    ;;
                4)
                    ./basic groups
                    SUBMENU=1
                    QUIT=1
                    ;;
                5)
                    ./basic 'history'
                    SUBMENU=1
                    QUIT=1
                    ;;

                6)
                    SUBMENU=1
                ;;
                esac


            done
        ;;
        2)
        
        ;;
        4)
            QUIT=1
        ;;




    esac





    done


#main_menu
