#!/bin/bash

# Setup binaries
GREP=/usr/bin/grep

# Function passwd
# Useage Example: passwd groupid ftp

function passwd {
    
    # Setup function variables
    SEARCH=$1
    USER=$2
   
    # Put some checks in for the script arguments
    if [[ -z "$SEARCH" ]] || [[ -z "$USER" ]] || [[ "$#" -ne "2" ]]; then
        (>&2 echo "You are missing a script argument. Usage: ./userman home user")
        exit -1
    fi

    # Delimiter used in the passwd file
    IFS=":"

    # Separates the found line with the delimiter provided.
    while IFS=: read -r username password userid groupid comment home shell
    do
        # Check the username exists before printing data to screen
        if [[ -z "$username" ]]; then
            (>&2 echo "The username: $USER does not exist")
            exit -2
        fi
        
        eval "echo \$$SEARCH"
    done <<< "$($GREP "^${USER}:" /etc/passwd)"
    return
}

# Call the function
passwd "$1" "$2"
exit 0
